### ISSUE TITLE
自动稳定性验证

### ISSUE THREAD

**Issue by Superjomn** [PaddlePaddle/MacroCE#28]
监测model repo的改动， 自动触发变更的model的稳定运行， 通过多次运行结果判断model的变更是否符合预期。 
teamcity 地址：
http://18.222.34.7:8080/viewType.html?buildTypeId=Paddle_CeTaskEvaluation

**Comment by guochaorong** [comment]
原来CE模型设置的merge监控，模型需要merge到CE模型库才能暴露问题。
本周增加CE 模型repo PR的监控告警。这样能够保证模型在merge到CE模型库之前 是能够保证功能正确，并且阈值在范围内

栗子：
https://github.com/Superjomn/paddle-ce-latest-kpis/pull/33

效果如下：
![image](https://user-images.githubusercontent.com/32069604/40461142-84606e86-5f3c-11e8-972c-9dd7870b5831.PNG)


点击details
http://18.222.34.7:8080/viewLog.html?buildId=450&buildTypeId=Paddle_CeTaskEvaluation
