### ISSUE TITLE
VGG16 模型 `flowers_32_train_speed` 指标异常

### ISSUE THREAD

**Issue by Superjomn** [PaddlePaddle/MacroCE#88]
值班日志 https://github.com/PaddlePaddle/continuous_evaluation/wiki/Duty-Records#20180628

判定为 https://github.com/PaddlePaddle/Paddle/pull/11690 引入的问题

**Comment by typhoonzero** [comment]
这就比较奇怪了，PR只改了一个环境变量的名字

**Comment by guochaorong** [comment]
这个数据有点尴尬
![aa](https://user-images.githubusercontent.com/32069604/42076163-80bbcb78-7ba6-11e8-809d-dc252681a123.JPG)

可能是上面那个commit的锅， 对应pr
https://github.com/PaddlePaddle/Paddle/pull/11496

**Comment by guochaorong** [comment]
春伟老师帮忙 revert了 11496， https://github.com/PaddlePaddle/Paddle/commit/6a06c56a32ad4c6681bb720aef800bbe4fc34470

数据正常，看起来是11496的锅


![mmm](https://user-images.githubusercontent.com/32069604/42086131-ccfef262-7bc4-11e8-93df-b8bd84c924b5.PNG)


http://18.222.34.7/commit/draw_scalar?task=vgg16

**Comment by guochaorong** [comment]
复现方法：
![kkk](https://user-images.githubusercontent.com/32069604/42087510-f9ca1a16-7bc8-11e8-82d4-cd56a5847753.JPG)

点击run


![mmm](https://user-images.githubusercontent.com/32069604/42087717-98213fd2-7bc9-11e8-9621-62499af9b7d5.JPG)

**Comment by typhoonzero** [comment]
Cool, Thanks!!

**Comment by Superjomn** [comment]
Revert 后PR 的测试 PASS

对应测试链接
http://ce.paddlepaddle.org:8080/viewLog.html?buildId=1291&buildTypeId=Paddle_ContinuousEvaluationDebug&tab=buildChangesDiv

**Comment by Superjomn** [comment]
![image](https://user-images.githubusercontent.com/328693/42122523-ce37e042-7c75-11e8-8cd4-40246a695cd9.png)
 revert 后，相关指标恢复正常
