### ISSUE TITLE
vgg模型的性能指标逐渐下降

### ISSUE THREAD

**Issue by Yancey0623** [PaddlePaddle/MacroCE#96]
![945c1e15aadea0447d3a8359d](https://user-images.githubusercontent.com/1426912/42889135-46eb9104-8adc-11e8-94be-d3da9da64953.png)

AWS->P40->V100 迁移过程中性能逐渐下降。

**Comment by guochaorong** [comment]
it's because the docker image on baidu machine is base on centos, which is 20% slower then ubuntu. and mostly env on baidu are still centos， so we should give priority to this.  
and we have plan to make a ubuntu cuda9 image,  which will be used for performance test to compare with tf.
